"""Web dashboard module.

Provides a Flask application that displays network monitoring statistics and
alerts generated by the threat detection module. The dashboard serves a
simple HTML page with periodic AJAX requests to fetch current host stats
and alert logs. It can be run directly via ``python -m jetson_network_monitor.dashboard``.
"""

import threading
from typing import List, Dict, Any

from flask import Flask, jsonify, render_template_string

from .analysis import TrafficAnalyzer


# HTML template for the dashboard page. In a full‑fledged application you
# would use separate template files and static assets. Here we embed it
# directly for simplicity.
_HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Jetson Network Monitor</title>
    <style>
        :root {
            --bg-1: #f5f8ff;
            --bg-2: #eef3ec;
            --panel: #ffffff;
            --ink: #182230;
            --muted: #5a6878;
            --line: #d9e1ec;
            --accent: #1264a3;
            --high: #c0392b;
            --medium: #d97706;
            --low: #1d7a46;
        }
        * { box-sizing: border-box; }
        body {
            margin: 0;
            color: var(--ink);
            background:
                radial-gradient(circle at 90% 10%, rgba(18, 100, 163, 0.10), transparent 26%),
                radial-gradient(circle at 10% 90%, rgba(29, 122, 70, 0.10), transparent 28%),
                linear-gradient(120deg, var(--bg-1), var(--bg-2));
            font-family: "IBM Plex Sans", "Segoe UI", sans-serif;
        }
        header {
            padding: 1.25rem 1rem 0.75rem;
            border-bottom: 1px solid var(--line);
            background: rgba(255, 255, 255, 0.75);
            backdrop-filter: blur(4px);
            position: sticky;
            top: 0;
            z-index: 5;
        }
        .title-row {
            display: flex;
            align-items: baseline;
            justify-content: space-between;
            gap: 1rem;
            flex-wrap: wrap;
        }
        h1 {
            margin: 0;
            font-family: "Space Grotesk", "IBM Plex Sans", sans-serif;
            font-size: 1.35rem;
            font-weight: 700;
        }
        .sub {
            color: var(--muted);
            font-size: 0.9rem;
        }
        main {
            padding: 1rem;
            display: grid;
            gap: 1rem;
        }
        .cards {
            display: grid;
            gap: 0.75rem;
            grid-template-columns: repeat(4, minmax(140px, 1fr));
        }
        .card {
            background: var(--panel);
            border: 1px solid var(--line);
            border-radius: 12px;
            padding: 0.9rem;
            box-shadow: 0 6px 18px rgba(12, 34, 64, 0.05);
        }
        .card .label { color: var(--muted); font-size: 0.82rem; }
        .card .value {
            margin-top: 0.25rem;
            font-size: 1.45rem;
            font-weight: 700;
            font-family: "Space Grotesk", "IBM Plex Sans", sans-serif;
        }
        .layout {
            display: grid;
            gap: 1rem;
            grid-template-columns: 1fr 1fr;
        }
        .panel {
            background: var(--panel);
            border: 1px solid var(--line);
            border-radius: 12px;
            padding: 0.9rem;
            box-shadow: 0 6px 18px rgba(12, 34, 64, 0.05);
        }
        .panel h2 {
            margin: 0 0 0.8rem 0;
            font-size: 1rem;
            font-family: "Space Grotesk", "IBM Plex Sans", sans-serif;
        }
        .bars { display: grid; gap: 0.6rem; }
        .bar-row { display: grid; gap: 0.3rem; }
        .bar-head {
            display: flex;
            justify-content: space-between;
            font-size: 0.85rem;
            color: var(--muted);
        }
        .bar {
            height: 9px;
            border-radius: 99px;
            background: #e5ecf6;
            overflow: hidden;
        }
        .bar > span {
            display: block;
            height: 100%;
            background: linear-gradient(90deg, #1d7a46, #1264a3);
        }
        .controls {
            display: flex;
            flex-wrap: wrap;
            gap: 0.5rem;
            margin-bottom: 0.8rem;
        }
        select, input {
            border: 1px solid var(--line);
            border-radius: 8px;
            padding: 0.45rem 0.55rem;
            background: #fff;
            color: var(--ink);
        }
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 0.92rem;
        }
        th, td {
            border-bottom: 1px solid var(--line);
            padding: 0.55rem;
            text-align: left;
            vertical-align: top;
        }
        th[data-sort] {
            cursor: pointer;
            user-select: none;
        }
        th[data-sort]:hover { color: var(--accent); }
        tbody tr:hover { background: #f7faff; }
        .mono { font-family: "Consolas", "JetBrains Mono", monospace; }
        .alerts { display: grid; gap: 0.5rem; max-height: 450px; overflow: auto; }
        .alert {
            border: 1px solid var(--line);
            border-left: 4px solid #9aa7b8;
            border-radius: 9px;
            padding: 0.6rem 0.7rem;
            background: #fff;
        }
        .alert.high { border-left-color: var(--high); background: #fff5f4; }
        .alert.medium { border-left-color: var(--medium); background: #fffaef; }
        .alert.low { border-left-color: var(--low); background: #f3fbf6; }
        .alert-top {
            display: flex;
            justify-content: space-between;
            gap: 0.5rem;
            flex-wrap: wrap;
            font-size: 0.82rem;
            color: var(--muted);
            margin-bottom: 0.2rem;
        }
        .badge {
            padding: 0.05rem 0.45rem;
            border-radius: 999px;
            font-size: 0.75rem;
            border: 1px solid #cfd8e4;
            background: #fff;
        }
        .empty {
            color: var(--muted);
            font-style: italic;
            padding: 0.5rem 0;
        }
        @media (max-width: 1060px) {
            .cards { grid-template-columns: repeat(2, minmax(140px, 1fr)); }
            .layout { grid-template-columns: 1fr; }
        }
        @media (max-width: 620px) {
            .cards { grid-template-columns: 1fr; }
            table { font-size: 0.84rem; }
            th, td { padding: 0.45rem; }
        }
    </style>
</head>
<body>
    <header>
        <div class="title-row">
            <h1>Jetson Network Monitor</h1>
            <div class="sub" id="last-updated">Waiting for first update...</div>
        </div>
    </header>
    <main>
        <section class="cards">
            <article class="card"><div class="label">Active Hosts</div><div class="value" id="summary-hosts">0</div></article>
            <article class="card"><div class="label">Total Packets Seen</div><div class="value" id="summary-packets">0</div></article>
            <article class="card"><div class="label">Total Traffic</div><div class="value" id="summary-bytes">0 B</div></article>
            <article class="card"><div class="label">Alerts (Last 15 min)</div><div class="value" id="summary-recent-alerts">0</div></article>
        </section>

        <section class="layout">
            <article class="panel">
                <h2>Top Talkers (By Packet Count)</h2>
                <div class="bars" id="top-talkers"></div>
            </article>
            <article class="panel">
                <h2>Alert Stream</h2>
                <div class="controls">
                    <select id="type-filter">
                        <option value="all">All Alerts</option>
                        <option value="traffic_flood">Traffic Flood</option>
                        <option value="port_scan">Port Scan</option>
                        <option value="ml_anomaly">ML Anomaly</option>
                        <option value="unknown_host">Unknown Host</option>
                    </select>
                    <input id="alert-search" type="text" placeholder="Filter by source IP">
                </div>
                <div class="alerts" id="alerts"></div>
            </article>
        </section>

        <section class="panel">
            <h2>Host Inventory</h2>
            <table id="host-table">
                <thead>
                    <tr>
                        <th data-sort="ip">Source IP</th>
                        <th data-sort="packets">Packets</th>
                        <th data-sort="bytes">Bytes</th>
                        <th data-sort="ports">Unique Ports</th>
                        <th data-sort="protocols">Protocols</th>
                        <th data-sort="last_seen">Last Seen</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </section>
    </main>
    <script>
        const PROTOCOL_NAMES = {
            "1": "ICMP",
            "6": "TCP",
            "17": "UDP"
        };

        const state = {
            stats: {},
            alerts: [],
            sortKey: "packets",
            sortDesc: true
        };

        function formatNumber(n) {
            return Number(n || 0).toLocaleString();
        }

        function formatBytes(bytes) {
            const units = ["B", "KB", "MB", "GB", "TB"];
            let value = Number(bytes || 0);
            let unitIndex = 0;
            while (value >= 1024 && unitIndex < units.length - 1) {
                value /= 1024;
                unitIndex += 1;
            }
            return `${value.toFixed(value < 10 && unitIndex > 0 ? 1 : 0)} ${units[unitIndex]}`;
        }

        function protocolSummary(protocolCounts) {
            const entries = Object.entries(protocolCounts || {});
            if (entries.length === 0) {
                return "none";
            }
            return entries
                .sort((a, b) => b[1] - a[1])
                .map(([proto, count]) => `${PROTOCOL_NAMES[String(proto)] || proto}:${count}`)
                .join(", ");
        }

        function alertSeverity(type) {
            if (type === "traffic_flood" || type === "port_scan") return "high";
            if (type === "ml_anomaly") return "medium";
            return "low";
        }

        function refreshSummary(hostRows, alerts) {
            const packetTotal = hostRows.reduce((acc, row) => acc + Number(row.info.packets || 0), 0);
            const byteTotal = hostRows.reduce((acc, row) => acc + Number(row.info.bytes || 0), 0);
            const recentCutoff = (Date.now() / 1000) - (15 * 60);
            const recentAlerts = alerts.filter(a => Number(a.timestamp || 0) >= recentCutoff).length;
            document.getElementById("summary-hosts").textContent = formatNumber(hostRows.length);
            document.getElementById("summary-packets").textContent = formatNumber(packetTotal);
            document.getElementById("summary-bytes").textContent = formatBytes(byteTotal);
            document.getElementById("summary-recent-alerts").textContent = formatNumber(recentAlerts);
        }

        function refreshTopTalkers(hostRows) {
            const mount = document.getElementById("top-talkers");
            mount.innerHTML = "";
            if (hostRows.length === 0) {
                mount.innerHTML = `<div class="empty">No hosts observed yet.</div>`;
                return;
            }
            const top = [...hostRows]
                .sort((a, b) => Number(b.info.packets || 0) - Number(a.info.packets || 0))
                .slice(0, 5);
            const maxPackets = Math.max(...top.map(item => Number(item.info.packets || 0)), 1);
            top.forEach(item => {
                const packets = Number(item.info.packets || 0);
                const width = Math.max(3, Math.round((packets / maxPackets) * 100));
                const row = document.createElement("div");
                row.className = "bar-row";
                row.innerHTML = `
                    <div class="bar-head"><span class="mono">${item.ip}</span><span>${formatNumber(packets)} pkts</span></div>
                    <div class="bar"><span style="width: ${width}%"></span></div>
                `;
                mount.appendChild(row);
            });
        }

        function sortedRows(statsObj) {
            const rows = Object.entries(statsObj || {}).map(([ip, info]) => ({ ip, info }));
            rows.sort((a, b) => {
                let av;
                let bv;
                if (state.sortKey === "ip") {
                    av = a.ip;
                    bv = b.ip;
                } else if (state.sortKey === "ports") {
                    av = (a.info.ports || []).length;
                    bv = (b.info.ports || []).length;
                } else if (state.sortKey === "protocols") {
                    av = Object.keys(a.info.protocols || {}).length;
                    bv = Object.keys(b.info.protocols || {}).length;
                } else {
                    av = a.info[state.sortKey] || 0;
                    bv = b.info[state.sortKey] || 0;
                }
                const order = av > bv ? 1 : av < bv ? -1 : 0;
                return state.sortDesc ? -order : order;
            });
            return rows;
        }

        function refreshHostTable(hostRows) {
            const tbody = document.querySelector("#host-table tbody");
            tbody.innerHTML = "";
            if (hostRows.length === 0) {
                tbody.innerHTML = `<tr><td colspan="6" class="empty">Waiting for packet data...</td></tr>`;
                return;
            }
            hostRows.forEach(({ ip, info }) => {
                const row = document.createElement("tr");
                const seenText = info.last_seen ? new Date(info.last_seen * 1000).toLocaleTimeString() : "n/a";
                row.innerHTML = `
                    <td class="mono">${ip}</td>
                    <td>${formatNumber(info.packets)}</td>
                    <td>${formatBytes(info.bytes)}</td>
                    <td>${(info.ports || []).length}</td>
                    <td>${protocolSummary(info.protocols)}</td>
                    <td>${seenText}</td>
                `;
                tbody.appendChild(row);
            });
        }

        function filteredAlerts(alerts) {
            const typeFilter = document.getElementById("type-filter").value;
            const text = document.getElementById("alert-search").value.trim().toLowerCase();
            return (alerts || []).filter(alert => {
                if (typeFilter !== "all" && alert.type !== typeFilter) {
                    return false;
                }
                if (!text) {
                    return true;
                }
                return String(alert.src_ip || "").toLowerCase().includes(text);
            });
        }

        function refreshAlerts(alerts) {
            const mount = document.getElementById("alerts");
            mount.innerHTML = "";
            if (alerts.length === 0) {
                mount.innerHTML = `<div class="empty">No alerts match the current filter.</div>`;
                return;
            }
            alerts.slice(-120).reverse().forEach(alert => {
                const severity = alertSeverity(alert.type);
                const when = alert.timestamp ? new Date(alert.timestamp * 1000).toLocaleTimeString() : "unknown time";
                const card = document.createElement("div");
                card.className = `alert ${severity}`;
                card.innerHTML = `
                    <div class="alert-top">
                        <span>${when}</span>
                        <span class="badge">${alert.type}</span>
                        <span class="mono">${alert.src_ip || "unknown"}</span>
                    </div>
                    <div>${alert.description || ""}</div>
                `;
                mount.appendChild(card);
            });
        }

        function refreshTimestamp() {
            document.getElementById("last-updated").textContent = `Last updated ${new Date().toLocaleTimeString()}`;
        }

        async function fetchData() {
            try {
                const [statsRes, alertsRes] = await Promise.all([
                    fetch('/data/host_stats'),
                    fetch('/data/alerts'),
                ]);
                state.stats = await statsRes.json();
                state.alerts = await alertsRes.json();
                const rows = sortedRows(state.stats);
                refreshSummary(rows, state.alerts);
                refreshTopTalkers(rows);
                refreshHostTable(rows);
                refreshAlerts(filteredAlerts(state.alerts));
                refreshTimestamp();
            } catch (err) {
                console.error('Error fetching dashboard data', err);
            }
        }

        document.querySelectorAll("th[data-sort]").forEach(th => {
            th.addEventListener("click", () => {
                const key = th.dataset.sort;
                if (state.sortKey === key) {
                    state.sortDesc = !state.sortDesc;
                } else {
                    state.sortKey = key;
                    state.sortDesc = true;
                }
                const rows = sortedRows(state.stats);
                refreshHostTable(rows);
            });
        });
        document.getElementById("type-filter").addEventListener("change", () => {
            refreshAlerts(filteredAlerts(state.alerts));
        });
        document.getElementById("alert-search").addEventListener("input", () => {
            refreshAlerts(filteredAlerts(state.alerts));
        });

        // refresh data every 2 seconds
        setInterval(fetchData, 2000);
        fetchData();
    </script>
</body>
</html>
"""


class DashboardServer(threading.Thread):
    """Thread running the Flask dashboard.

    It exposes endpoints to fetch host statistics and alerts as JSON and serves
    a simple HTML dashboard. Alerts are consumed from an alert queue and
    stored locally for display.
    """

    def __init__(self, analyzer: TrafficAnalyzer, alert_queue: "queue.Queue", host: str = "0.0.0.0", port: int = 5000):
        super().__init__(daemon=True)
        self.analyzer = analyzer
        self.alert_queue = alert_queue
        self.host = host
        self.port = port
        self.app = Flask(__name__)
        self.alerts: List[Dict[str, Any]] = []
        # set up routes
        self._setup_routes()
        self._stop_event = threading.Event()

    def _setup_routes(self) -> None:
        @self.app.route('/')
        def index():
            return render_template_string(_HTML_TEMPLATE)

        @self.app.route('/data/host_stats')
        def get_host_stats():
            stats = self.analyzer.host_stats
            # convert sets to lists for JSON serialization
            for host, info in stats.items():
                info['ports'] = list(info['ports'])
            return jsonify(stats)

        @self.app.route('/data/alerts')
        def get_alerts():
            # move alerts from queue into local store
            self._drain_alerts()
            return jsonify(self.alerts[-500:])  # return recent alerts for dashboard filtering

    def _drain_alerts(self) -> None:
        while True:
            try:
                alert = self.alert_queue.get_nowait()
            except Exception:
                break
            self.alerts.append(alert)
        # prevent unbounded growth during long monitoring sessions
        self.alerts = self.alerts[-2000:]

    def stop(self) -> None:
        self._stop_event.set()

    def run(self) -> None:
        # start Flask server; note this blocks until process exit
        # we call app.run in a separate thread to allow stop() to be used
        # gracefully. However, Flask's built‑in server cannot be stopped
        # elegantly once started, so stop() is best effort.
        self.app.run(host=self.host, port=self.port, threaded=True)
